language: cpp 
os:
  - linux
complier:
  - gcc 
  - clang 
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - lcov
script:
   bash initialSetup.sh
   bash pullAndBuild.sh
